### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by jpbronsted** [jpbronsted/CameroonSite#1]
Create a skeleton for the home page. It needs to include the following features:
 - Some text describing the current crisis in Ambazonia
 - A deathcount

Potential extra features could include some small sample of the images from the database. For this, I would just set up some HTML entity that can house images so that later we can add a script that loads the images and inserts them.

**Comment by tamara-tsubota** [comment]
Where are we getting the deathcount from?

**Comment by jpbronsted** [comment]
I would make some sort of UI that displays a number and clearly labels it as a deathcount. Have that number be generated by a script but just set it to zero (something like `<script type='type/javascript'>count = 0;</script>` would be fine as long as the number stored in count is being displayed). In a future sprint, we can connect it to a database or some other entity.

**Comment by jpbronsted** [comment]
Why was this closed?
