### ISSUE TITLE
Connect Document Fetch to the Database

### ISSUE THREAD

**Issue by jpbronsted** [jpbronsted/CameroonSite#17]
Add a document fetch component to results.php that queries the database for a list of documents based on the input form. Try to make sure that we have some way of distinguishing which results are photos, which are documents, and which are audio recordings so that if we have to disambiguate between the document types to make the display interface happy, we can do so.

**Comment by tamara-tsubota** [comment]
I'm confused on my task. Is it just to populate the dropdown with the document types?

**Comment by jpbronsted** [comment]
Not quite. We need to grab documents from Firebase Storage based on queries in the database. We haven't established a protocol yet for storing files and referencing them in the database yet, so let's hold off on too much development here until we've agreed to one. I'll try to set up a meeting tomorrow so that Web Dev and Android people can collaborate on that.
